//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.comentario = new HashSet<comentario>();
            this.participante = new HashSet<participante>();
            this.pergunta = new HashSet<pergunta>();
        }
    
        public int Id { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> id_principal { get; set; }
        public string Nome { get; set; }
        public string Responsavel { get; set; }
        public bool Cancelado { get; set; }
        public string palavra_chave { get; set; }
        public string palavra_chave2 { get; set; }
        public short limite_participantes { get; set; }
        public string Local { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> data_hora_fim { get; set; }
        public Nullable<bool> emitidos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentario { get; set; }
        public virtual evento_composto evento_composto { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participante> participante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pergunta> pergunta { get; set; }
    }
}
