//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventosEntities : DbContext
    {
        public EventosEntities()
            : base("name=EventosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comentario> comentarios { get; set; }
        public virtual DbSet<evento> eventoes { get; set; }
        public virtual DbSet<evento_composto> evento_composto { get; set; }
        public virtual DbSet<pergunta> perguntas { get; set; }
        public virtual DbSet<resposta> respostas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
