//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class participante
    {
        public string login { get; set; }
        public int id_evento { get; set; }
        public Nullable<bool> Presenca { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
