//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class resposta
    {
        public int Id { get; set; }
        public string usuario { get; set; }
        public int id_pergunta { get; set; }
        public string resposta1 { get; set; }
    
        public virtual pergunta pergunta { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
